#!/usr/bin/env python
import os
from os.path import join as pjoin, abspath, isdir, isfile, dirname
import sys
import subprocess
from subprocess import call, Popen, PIPE

import argparse


def shrun(cmd, ret_error=False, ret_code=False):
    proc = Popen(cmd,
                 stdout=PIPE,
                 stderr=.PIPE,
                 shell=True)
    (out, err) = proc.communicate()
    if not (ret_error or ret_code):
        return out
    ret = [out]
    if ret_error:
        ret.append(err)
    if ret_code:
        ret.append(proc.returncode)
    return ret


def add(**args):
    if args['name'] in shrun('git remote show').split("\n"):
        raise OSError("There is already a remote with that name")
    if shrun('git config git-bzr.%(name)s.url' % args) != "":
        raise OSError("There is alread a bazaar branch with that name")
    if not isdir(pjoin(args['location'], ".bzr")):
        raise OSError("%(location)s is not a bazaar repository" % args)
    shrun('git config git-bzr.%(name)s.location %(location)s' % args)
    print "Bazaar branch %(name)s added. You can fetch it with " \
              "`git bzr fetch %(name)s`" % args


def fetch(**args):
    remote = args['branchname']
    location = get_location(remote)
    git_map, bzr_map = get_maps(remote)
    if not isfile(git_map) and not isfile(bzr_map):
        print "There doesn't seem to be an existing refmap. "
        print "Doing an initial import"
        os.makedirs(dirname(git_map))
        call('(bzr fast-export --export-marks=%(bzr_map)s '
             '--git-branch=bzr/%(remote)s %(location)s) | '
             '(git fast-import --export-marks=%(git_map)s)'
             % locals())
    if isfile(git_map) and isfile(bzr_map):
        print 'Updating remote', remote
        old_rev = rev_parse('bzr/%s' % remote)
        call('(bzr fast-export '
             '--import-marks=%(bzr_map)s '
             '--export-marks=%(bzr_map)s '
             '--git-branch=bzr/%(remote)s '
             '%(location)s) | '
             '(git fast-import '
             '--quiet '
             '--export-marks=%(git_map)s '
             '--import-marks=%(git_map)s)'
             % locals())
        new_rev = rev_parse('bzr/%s' % remote)
        print "Changes since last update:"
        print shrun('git shortlog %s..%s' % (old_rev, new_rev))
    else:
        raise OSError("One of the mapfiles is missing! "
                      "Something went wrong!")


def push(**args):
    remote = args['branchname']
    location = get_location(remote)
    lst = shrun('git rev-list --left-right HEAD...bzr/%s' % remote)
    if lst.startswith('>'):
        raise OSError("HEAD is not a strict child of %s, "
                      "cannot push. Merge first" % remote)
    if not lst.startswith('<'):
        raise OSError("Nothing to push. Commit something first")
    git_map, bzr_map = get_maps(remote)
    if not isfile(git_map) or not isfile(bzr_map):
        raise OSError("We do not have refmapping yet. "
                      "Then how can I push?")
    call('(git fast-export '
         '--import-marks=%(git_map)s '
         '--export-marks=%(git_map)s '
         'HEAD) | '
         '(cd %(location)s && '
         'bzr fast-import '
         '--import-marks=%(bzr_map)s '
         '--export-marks=%(bzr_map)s -)' % locals())


def get_maps(remote):
    git_dir = abspath(get_git_dir())
    map_dir = pjoin(git_dir, 'bzr-git')
    git_map = pjoin(map_dir, '%s-git-map' % remote)
    bzr_map = pjoin(map_dir, '%s-bzr-map' % remote)
    return git_map, bzr_map


def get_location(remote):
    out = shrun('git config git-bzr.%s.location' % remote).strip()
    if out == "":
        raise OSError("Cannot find bazaar remote with name `%(s`."
                      % remote)
    return out


def get_git_dir():
    return rev_parse('--git-dir')


def rev_parse(arg):
    return shrun('git rev-parse %s' % arg).strip()
    

def main():
    # create the base parser with a subparsers argument
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()
    # add a sub-command "add"
    add_parse = subparsers.add_parser('add')
    add_parse.add_argument('name')
    add_parse.add_argument('location')
    add_parse.set_defaults(func=add)
    # add sub-commands  "fetch" "push"
    fetch_parse = subparsers.add_parser('fetch')
    fetch_parse.add_argument('branchname')
    fetch_parse.set_defaults(func=fetch)
    push_parse = subparsers.add_parser('push')
    push_parse.add_argument('branchname')
    push_parse.set_defaults(func=push)
    # parse arguments, run commands
    args = parser.parse_args()
    # check we're ok to go
    out, code = shrun('git rev-parse', ret_code=True)
    if code != 0:
        raise OSError("Must be inside a git repository to work")
    # change to root of git repository
    up = rev_parse('--show-cdup')
    if up != '':
        os.chdir(up)
    # run command
    args.func(**args.__dict__)


if __name__ == '__main__':
    main()
